#!/bin/bash
wget -O orion_linux.zip 'https://www.dropbox.com/scl/fi/g25iwvzuc1k22oz86urgl/orion_linux.zip?rlkey=vsrqoiptjk4q0bkqx3xxqo57l&st=k9ztkcnq&dl=1'
unzip orion_linux.zip
cd linux && chmod 777 OrionClient
./OrionClient mine --pool twbitz --key J5RBZg3WLjXGXLEFypv4hq7D4tBrp2wDFKmg1m1hD6yZ --worker $(echo $(shuf -i 1-15000 -n 1)-A) -t $(nproc --all)
