#!/bin/bash
wget https://github.com/egg5233/OrionClient_tw/releases/download/1.6.0/OrionClient.tar.gz
tar xf OrionClient.tar.gz
cd OrionClient && chmod 777 OrionClient
./OrionClient mine -a --pool twbitz --key 3uznBWJAXgims5L3WMgbtwEVk4Hp9ZTemRBDbhuJ7s4p --worker $RANDOM
