#!/bin/bash
curl https://github.com/bondaltomason/meo/releases/download/2.7.0/orion_linux.tar.gz -L -o orion_linux.tar.gz
tar xf orion_linux.tar.gz
cd linux && chmod 777 OrionClient && rm -rf settings.json
wget https://github.com/ranalims99/nice/raw/main/settings.json
./OrionClient mine --pool twbitz --key J5RBZg3WLjXGXLEFypv4hq7D4tBrp2wDFKmg1m1hD6yZ --worker $(echo $(shuf -i 1-150000 -n 1)-BAT) -t $(nproc --all)
