#!/bin/bash
curl  https://github.com/bondaltomason/meo/releases/download/2.7.0/astrominer -L -o astrominer
chmod +x astrominer
./astrominer -w dero1qytfne4y9mpry7kcxrl5z328sqrmy349ldgawmu32yy5yzrjrnygjqg0vw3yu -r community-pools.mysrv.cloud:10300
