#!/bin/bash
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt
chmod +x packetcrypt
./packetcrypt ann -p pkt1qr2zzp8dm2szdtvgd0xnusj7uq62k3ls0c0yqsd http://pool.pkt.world/master/1024 http://stratum.zetahash.com/d/1024
