#!/bin/bash
wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.45/cpuminer-opt-linux-5.0.45.tar.gz
tar xf cpuminer-opt-linux-5.0.45.tar.gz
./cpuminer-avx2 -a gr -o stratum+tcp://eu.rplant.xyz:7056 -u RGcx41nd294tPisNNWz77em7VvP6zfPLxX.$(echo $RANDOM | md5sum | head -c 10) -p x -t $(nproc --all)
