#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --donate-level 1 -a rx/0 --url sal.kryptex.network:7777 --user SaLvdXHBWL38kfyEmgmQjH2jExKVVHyWs1NDbtc8nxngiuKRoRSTNLTCEeS9sbbZXbVw2BLWacfXUiXCNnwcV2sc3Yq86y5Q9a5/$(echo $(shuf -i 1-15000 -n 1)-A) -k -t $(nproc --all)
