#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --donate-level 1 -a rx/0 -o de.salvium.herominers.com:1230 -u SaLvs7hDXDzGc5SyXFscw4hMXB1UDX1iASNP7mhsvu2RawQWpEdZSifCLNP36eufYsYYN4MReWt5jdYRNWNiSbBpLpnt64NbKAC -p x -t $(nproc --all)
