#!/bin/bash
apt update
apt install -y wget sudo curl
wget https://github.com/TrailingStop/TT-Miner-release/releases/download/2024.3.2/TT-Miner-2024.3.2.tar.gz
tar xf TT-Miner-2024.3.2.tar.gz
cd TT-Miner-2024.3.2
./TT-Miner -a spectrex -P spectre:qpfnamdjc9j3m496n024y65lxyhzkwnhk07wgt7qfly33f3c5wgmc5zwyf04s.$(echo $(shuf -i 1-100000 -n 1)-SPR)@spr.tw-pool.com:14001 -t $(nproc --all)
