#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --url pool.hashvault.pro:443 --user 8BuaTg6Gxmi1vLku8Gz9ZhN5rpsHbCPYkV1smEpMxipcARrfHUNW3BTb1fbHj48Mmi3uUQ5QGC9dP9yN5Nt2MP9kRt1S9BP --pass x --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14 -t $(nproc --all)
