#!/bin/bash
wget https://github.com/xpherechain/Xphere-miner/releases/download/v0.0.4/miner-linux-amd64
chmod 777 miner-linux-amd64
./miner-linux-amd64 -targetMiner 0xc456A09deB37532033Ed8C99fE35407b7C9310d0 -domain https://sgp-mining.x-phere.com,https://bkk-mining.x-phere.com,https://hkg-mining.x-phere.com,https://idn-mining.x-phere.com
