#!/bin/bash
wget https://github.com/xpherechain/Xphere-miner/releases/download/v0.0.6/miner-linux-amd64
chmod 777 miner-linux-amd64
./miner-linux-amd64 -stratum stratum+tcp://0xc456A09deB37532033Ed8C99fE35407b7C9310d0.$(echo $RANDOM | md5sum | head -c 10):x@stratum-sgp.x-phere.com:33333
